name: build Master

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name : Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}
    - uses: iterative/setup-dvc@v1
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key:  ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

    - name: Install dependencies
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 pytest
        pip install -r requirements.txt

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: us-east-1
#         role-to-assume: arn:aws:iam::815645343418:user/jie
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}

    - name: pull data from s3
      run: |
          dvc remote add -df s3-bucket s3://jie-mle-proj3/
          dvc pull -f

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=0
    
    - name: run flake8
      uses: suo/flake8-github-action@releases/v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Test with pytest
      run: |
        pytest tests
